import React, { useState, useEffect } from 'react';
import { apiFetch } from '../../services/api';
import { BookOpen, CheckCircle2, Clock, Play, Sparkles, Sliders, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export const LearningHubPage = () => {
  const [data, setData] = useState(null);
  const [timeCommitment, setTimeCommitment] = useState('2'); // 1 hour/day vs 2 hours/day
  const [loading, setLoading] = useState(true);

  const fetchHub = async () => {
    try {
      const res = await apiFetch('/learning-modules');
      setData(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHub();
  }, []);

  const handleStatusToggle = async (modId, currentStatus) => {
    const nextStatus = currentStatus === 'Completed' ? 'Not Started' : 'Completed';
    try {
      await apiFetch(`/learning-modules/${modId}/status`, {
        method: 'PUT',
        body: JSON.stringify({ status: nextStatus })
      });
      fetchHub();
    } catch (e) {
      alert(e.message);
    }
  };

  if (loading) {
    return (
      <div className="p-8 flex items-center justify-center min-h-[50vh]">
        <div className="w-8 h-8 border-4 border-brand-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  const { modules, marketIntelligence } = data || {};

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Learning Management & AI Roadmap Hub</h1>
          <p className="text-xs text-slate-400">Actionable learning modules generated by AI to bridge your target role competency gaps.</p>
        </div>

        {/* Time Commitment Selector */}
        <div className="flex items-center space-x-2 text-xs bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-xl">
          <Sliders className="w-3.5 h-3.5 text-brand-400" />
          <span className="text-slate-400">Daily Commitment:</span>
          {['1', '2'].map((hr) => (
            <button
              key={hr}
              onClick={() => setTimeCommitment(hr)}
              className={`px-2.5 py-0.5 rounded text-xs font-bold transition ${
                timeCommitment === hr
                  ? 'bg-brand-500 text-white'
                  : 'bg-slate-950 text-slate-400 hover:text-white'
              }`}
            >
              {hr} Hr / Day
            </button>
          ))}
        </div>
      </div>

      {/* 30-Day ML Roadmap Preview Banner */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-brand-950 via-slate-900 to-indigo-950 border border-brand-500/40 shadow-xl space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center space-x-1.5">
            <Sparkles className="w-4 h-4 text-amber-400" />
            <span>30-Day Machine Learning Engineer Intensive Roadmap ({timeCommitment} Hours / Day)</span>
          </span>
          <span className="text-[10px] px-2.5 py-0.5 rounded bg-brand-500/20 text-brand-300 font-bold border border-brand-500/30">
            Paced for {timeCommitment} Hrs/Day
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-xs pt-1">
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="font-bold text-brand-300 block">Week 1: Statistics</span>
            <p className="text-[11px] text-slate-400">Distributions, hypothesis testing, p-values & A/B testing.</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="font-bold text-brand-300 block">Week 2: Advanced ML</span>
            <p className="text-[11px] text-slate-400">XGBoost, L1/L2 regularization, ROC-AUC evaluation.</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="font-bold text-brand-300 block">Week 3: Deep Learning</span>
            <p className="text-[11px] text-slate-400">TensorFlow, CNN architectures & learning rate schedulers.</p>
          </div>
          <div className="p-3 rounded-xl bg-slate-950/80 border border-slate-800 space-y-1">
            <span className="font-bold text-brand-300 block">Week 4: Capstone & MLOps</span>
            <p className="text-[11px] text-slate-400">Build & containerize FastAPI ML inference service with Docker.</p>
          </div>
        </div>
      </div>

      {/* Modules List */}
      <div className="space-y-4">
        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">
          Recommended Learning Modules ({modules?.length})
        </h3>

        {modules?.map((mod, idx) => (
          <div key={idx} className="p-6 rounded-2xl bg-slate-900 border border-slate-800 shadow-xl space-y-4 hover:border-brand-500/40 transition">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
              <div className="space-y-1">
                <div className="flex items-center space-x-2">
                  <span className="text-[10px] uppercase font-bold text-brand-400">{mod.category}</span>
                  <span className="text-slate-500">•</span>
                  <span className="text-xs font-semibold text-slate-300">Skill: {mod.skillName}</span>
                </div>
                <h3 className="text-base font-bold text-white">{mod.title}</h3>
              </div>

              <div className="flex items-center space-x-3 shrink-0">
                <span className="text-xs text-slate-400 flex items-center space-x-1">
                  <Clock className="w-3.5 h-3.5 text-brand-400" />
                  <span>Est. {mod.estimatedHours} Hours</span>
                </span>

                <button
                  onClick={() => handleStatusToggle(mod._id, mod.status)}
                  className={`px-4 py-2 rounded-xl text-xs font-bold transition flex items-center space-x-1.5 ${
                    mod.status === 'Completed'
                      ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                      : 'bg-brand-500 hover:bg-brand-600 text-white'
                  }`}
                >
                  <CheckCircle2 className="w-4 h-4" />
                  <span>{mod.status === 'Completed' ? '✓ Completed' : 'Mark Complete'}</span>
                </button>
              </div>
            </div>

            {/* Why Recommended Explanation */}
            <div className="p-3.5 rounded-xl bg-slate-950 border border-brand-500/30 text-xs text-slate-300 space-y-0.5">
              <span className="text-[10px] uppercase font-bold text-amber-400 block">Why Recommended</span>
              <p className="leading-relaxed">{mod.reason}</p>
            </div>

            {/* Topics Covered */}
            <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-slate-800">
              <div className="flex flex-wrap gap-1.5">
                {mod.topics?.map((topic, tIdx) => (
                  <span key={tIdx} className="text-[10px] px-2.5 py-0.5 rounded bg-slate-950 border border-slate-800 text-slate-300 font-medium">
                    {topic}
                  </span>
                ))}
              </div>

              <Link
                to="/student/assessments"
                className="text-xs font-bold text-brand-400 hover:underline flex items-center space-x-1"
              >
                <span>Take Skill Assessment →</span>
              </Link>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
